

#########
POST http://localhost:1337/api/register
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}

#########
POST http://localhost:1337/api/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}

#########
GET http://localhost:1337/api/search/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmYwMjZmMTFiYTlhMTM4NmUzMTkzMSIsImlhdCI6MTc1MjEwNTU5NiwiZXhwIjoxNzUyMTA5MTk2fQ.AXfPctR8Q_t4jtQMRgHA12sfJfVar89lmx9x5we1knY

#########

POST http://localhost:1337/api/login
Content-Type: application/json

{
  "email": "sadmin@gmail.com",
  "password": "123456"
}

#########


POST  http://localhost:1337/api/auth/dynamic-models
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Nzg4OTBiMGFjMTczZTAyOTg1NDdiZCIsImlhdCI6MTc1MjczMDA0NSwiZXhwIjoxNzUyNzczMjQ1fQ.tmsQymQeUUxUGt0QIRJEaTb9xe2N_Q90KibtaRGFQCw

{"name":"test","displayName":"test","fields":[{"name":"n","type":"string","required":false}]}

#########

POST http://localhost:1337/api/auth/dynamic-data/Test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Nzg4OTBiMGFjMTczZTAyOTg1NDdiZCIsImlhdCI6MTc1MjczMDA0NSwiZXhwIjoxNzUyNzczMjQ1fQ.tmsQymQeUUxUGt0QIRJEaTb9xe2N_Q90KibtaRGFQCw

{"data": {"n": "sample value"}}

#########

# Get dynamic data
GET http://localhost:1337/api/auth/dynamic-data/Test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Nzg4OTBiMGFjMTczZTAyOTg1NDdiZCIsImlhdCI6MTc1MjczMDA0NSwiZXhwIjoxNzUyNzczMjQ1fQ.tmsQymQeUUxUGt0QIRJEaTb9xe2N_Q90KibtaRGFQCw