POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "chodung",
    "password": "123456"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "chodung2",
    "password": "123456"
} 

###

DELETE http://localhost:5000/api/post/6603befddd430c15bd50eaed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAwMTJkNGRmYTJkZTQ4NTViYmNkODEiLCJpYXQiOjE3MTE0OTA5NTB9.EyqfflJtPQgaIlwgyFtAb8p2-jMXEtclBWBe5u2pmCU

###

PUT http://localhost:5000/api/profile/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjRhZDQ0N2U3MGNmNzIwOTY4ZjZjNGQiLCJpYXQiOjE3MTYxODAxMDl9.Iwtcc8EFDQndVSDhGaMzKFUXVpF__u_1C3DnCnPT-uA

{
    "bio": "sdfsà",
    "birthday": "2024-05-23T00:00:00.000Z",
    "email": "email@gmail.com",
    "fullname": "fullname abcaaaa",
    "gender": "female",
    "phone": "0123456780",
    "price": 99,
    "speciality": "Corporate Law"
}    

###
GET http://localhost:5000/api/appointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFmYmQ4Njk5MTJlYzg0ZTBhYWIyZmEiLCJpYXQiOjE3MTU3ODkxNDV9.xC66imlYDZFsqO2R0W06-PcdymLLXTG4n4g8E0PSmz0

###

GET http://localhost:5000/api/appointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFmYmQ4Njk5MTJlYzg0ZTBhYWIyZmEiLCJpYXQiOjE3MTU3ODkxNDV9.xC66imlYDZFsqO2R0W06-PcdymLLXTG4n4g8E0PSmz0


###

POST http://localhost:5000/api/appointment/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFmYmQ4Njk5MTJlYzg0ZTBhYWIyZmEiLCJpYXQiOjE3MTU3ODkxNDV9.xC66imlYDZFsqO2R0W06-PcdymLLXTG4n4g8E0PSmz0

{
    "lawyer": "663e0b41e49187d1234d8df5",
    "date": "1/1/1111",
    "time": "1:00",
    "description": "description"
}

###

GET http://localhost:5000/api/profile/expert/663e0b41e49187d1234d8df5
Content-Type: application/json

###

POST http://localhost:5000/api/expert/search
Content-Type: application/json

{
  "fullname": "name",
  "gender": "male",
  "speciality": "",
  "minPrice": 100,
  "maxPrice": 500
}

###

GET http://localhost:5000/api/profile/user/660012d4dfa2de4855bbcd81
Content-Type: application/json

###

PUT http://localhost:5000/api/profile/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNlMGI0MWU0OTE4N2QxMjM0ZDhkZjUiLCJpYXQiOjE3MTYxNzU0Mzl9.vI9s2nes2pAwZKaqvVjobY8G3OJUuiIXgrWLmEjs2VA

{
    "CurrentPassword": "1234567",
    "password": "123456"
}









###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "chodung2",
    "password": "123456"
}